### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by mhuebert** [mhuebert/instaparse-live#4]
I am beginning to think about options that would be useful to set for the parser:
- **:output** - [*:visual | :hiccup | :enlive]
- **:unhide** - [:content | :tags | :all]
- **:partial** - Boolean [*false]
- **:total** - Boolean [*false]
- **:max-parses** - Number [*50]
- **:start** - [<:rule-name>] - set an arbitrary rule to be the "starting production"
- **:input-fomat** - [*:ebnf | :abnf]

Any feedback about these options would be welcome (cc/ @aengelberg @lbradstreet)

The interface may be as simple as a collapsible panel in which you can write/modify the map of options yourself in Clojure. eg:

``` clj
{
  :output :visual ;/ :hiccup, :enlive
  :max-parses 50
  :partial false
  :total false
  :input-format :ebnf
  ; :unhide :content ;/ :content, :tags, :all
  ; :start :rule-name  
}
```

**Comment by aengelberg** [comment]
Great idea. You will need to think about what should happen (from a CSS standpoint) when both `:total true` and `:output :visual` are enabled, because an instaparse failure tag may be somewhere in the final data structure.

**Comment by canweriotnow** [comment]
Any chance of grammar type being a settable option (ebnf/abnf/etc)?

**Comment by mhuebert** [comment]
@canweriotnow Good catch, I missed that. I've added it to the sample above to reference when implementing.

**Comment by mhuebert** [comment]
OK, I've got most of this working in the firebase branch. The options panel is just a EDN map which is read by ClojureScript and fed into the `parser` and `parses` functions.

![screen shot 2015-06-17 at 4 03 26 pm](https://cloud.githubusercontent.com/assets/165223/8208928/6f1d8772-150a-11e5-9b7c-3a53898e2b0f.png)

One thing I am not sure of is how to render `:enlive` or if that even makes sense.

**Comment by aengelberg** [comment]
That looks really awesome!

I don't see how enlive is a problem. It sounds like what you call the `:hiccup` option is printing the hiccup sexpr, so that could easily translate to enlive. Note that you may want to be pretty-printing the hiccup output to get nice indenting. Perhaps you could use fipp if the default pretty-printer is too slow.

**Comment by mhuebert** [comment]
@aengelberg you were right - it wasn't a problem. I just had to use the latest snapshot of instaparse-cljs, so that I could bump my Clojure(Script) versions (necessary to get pprint/fipp to work). Thanks for the tip!
