### ISSUE TITLE
Optimize reactive computation

### ISSUE THREAD

**Issue by aengelberg** [mhuebert/instaparse-live#5]
Currently, if only the parse input is changed, the grammar is needlessly recomputed due to the nature of the reagent flow.

There should be a way in reagent to pull from both atoms one at a time (in separate components) in a way that only requires re-computing the parser when the grammar is edited.

**Comment by mhuebert** [comment]
Yeah I'll look at this. Maybe I can just memorize the parse function. Or
have the atom that is dereferenced in the output component store the parsed
grammar rather than the grammar text.

**Comment by mhuebert** [comment]
Fixed in 0f2e925a756339b5e06756f92d30433a58e6790c with a custom memoize function (only remembers the last args/result)
