### ISSUE TITLE
Allow disabling "auto" parsing

### ISSUE THREAD

**Issue by aengelberg** [mhuebert/instaparse-live#6]
When editing large grammars and inputs, it may become cumbersome to wait a fraction of a second after typing every character (depending on how slow the JavaScript engine is in your browser), especially because the application is single-threaded. I think it would be useful to have a checkbox (toggled on by default) that specifies whether the parse should be recomputed at all times. If not, there would be a button "Parse" that could be clicked to update the output (perhaps with a keyboard shortcut available).

Does that feature sound useful? Perhaps it doesn't go with the spirit of the environment that this project aims to provide, in which case you don't have to include it.

**Comment by mhuebert** [comment]
Good point.. a couple possibilities:
- a 'debounce' on key press, so that it will only recompute after you've
  stopped typing for, say, 300ms (configurable) - i think it takes _away_
  from the snappy feel if you can't type quickly
- a keyboard shortcut (cmd-r)

**Comment by mhuebert** [comment]
I played around with webworkers on a new branch: https://github.com/mhuebert/instaparse-live/tree/webworker

After playing with `servant` for awhile, tried using the webworkers api directly. Even a bare-bones example-case using webworkers is noticeably sluggish.

I'm inclined to forego webworkers and instead add an `auto-parse` option (as you suggested) along with a keyboard shortcut (I'm thinking <s>`ctrl-p`</s> `ctrl-r`).

**Comment by mhuebert** [comment]
Finished in e462d0db406d4d3bc5c003ec47e9c7de292fb665.

To use, set :auto-update to false in the options map, then `ctrl-r` (or click the button in the header) to refresh. After setting the option back to true, you have to refresh one more time manually to pick up the change.

The way this works: I keep a map of all CodeMirror instances on the page in state/ui. Each editor is associated with an atom (or in this case a cursor) which is updated on every keystroke, _unless_ :auto-update is false—in which case the current state is invisible to the app and only known to the CodeMirror instance. Hitting refresh loops through the list of editors and updates each editor's atom with its current value. When an editor's atom is updated, reactions that depend on it are re-run, thanks to reagent.
