### ISSUE TITLE
Saving and loading seems nonfunctional

### ISSUE THREAD

**Issue by kg** [mhuebert/instaparse-live#9]
I wrote a simple grammar and some test text, saving it a few times after logging in via github.

Taking the URL and pasting it into a new browser tab resulted in a partial load, where the grammar and input text fields were unpopulated but the parsed output at the bottom indicated that it had loaded the grammar and input text.

Hitting 'save' blew away the saved grammar / input text and completely destroyed my work. Any attempt to load previous revisions or even load the specific current revision renders a blank page. :-(

**Comment by mhuebert** [comment]
Hi Katelyn,

I'm taking a look now. It looks like your work is not lost, but is not
loading correctly. I will try to fix asap. In the meantime if you'd like me
to send you the text you can either comment here & I'll post a link to a
gist, or email me at me@matt.is.

**Comment by kg** [comment]
No rush. I ended up rewriting the grammar from scratch and saving it externally. Instaparse live is still a neat, useful tool.

I've been hitting serious performance issues but I assume those aren't related to instaparse live but instead the domain of instaparse. Your option to disable auto refresh helped.

On July 30, 2015 1:53:13 PM PDT, Matt Huebert notifications@github.com wrote:

> Hi Katelyn,
> 
> I'm taking a look now. It looks like your work is not lost, but is not
> loading correctly. I will try to fix asap. In the meantime if you'd
> like me
> to send you the text you can either comment here & I'll post a link to
> a
> gist, or email me at me@matt.is.
> 
> On Thu, Jul 30, 2015 at 10:06 PM, Katelyn Gadd
> notifications@github.com
> wrote:
> 
> > I wrote a simple grammar and some test text, saving it a few times
> > after
> > logging in via github.
> > 
> > Taking the URL and pasting it into a new browser tab resulted in a
> > partial
> > load, where the grammar and input text fields were unpopulated but
> > the
> > parsed output at the bottom indicated that it had loaded the grammar
> > and
> > input text.
> > 
> > Hitting 'save' blew away the saved grammar / input text and
> > completely
> > destroyed my work. Any attempt to load previous revisions or even
> > load the
> > specific current revision renders a blank page. :-(
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mhuebert/instaparse-live/issues/9.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mhuebert/instaparse-live/issues/9#issuecomment-126483183
- kg (mobile)

**Comment by mhuebert** [comment]
ok, it's fixed & the data is safe - it was an issue with refreshing the
page. sorry for the trouble!
